### PR TITLE
docs(README): add English document

### PR DESCRIPTION
**Pull request by XadillaX**
**Changes** (At least one)

- [x] Documents

**Milestone?**

- [x] No

**Checklist**

- [x] To **dev** branch
- [x] Match Standard [ESLint](http://standardjs.com)
- [x] Rebased and tidy commit message
- [x] Description in title
- [x] Passed all test

**Other information**

### CODE REVIEW

**Comment by XadillaX** [comment]
/cc @onluiz

Are you interested in reviewing this PR?

**Comment by aganglada** [comment]
Sure! Thanks!

**Comment by xinyu198736** [comment]
@aganglada 
We are developing the English version of the application。

**Comment by aganglada** [comment]
That's super nice news! Keep it up :)

**Pull request merged**
